version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper

  order-service:
    build: ./order_service
    ports:
      - "4000:4000"
    depends_on:
      - kafka

  kitchen-service:
    build: ./kitchen_service
    depends_on:
      - kafka

  delivery-service:
    build: ./delivery_service
    depends_on:
      - kafka

  status-service:
    build: ./status_service
    ports:
      - "5000:5000"
    depends_on:
      - kafka

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - status-service
